name: vizgen-snakemake
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - snakemake==7.32.4
      - pulp<2.8
      - vpt
      - vpt-plugin-cellpose2
      - stardist
      - tensorflow
